spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/librarydb?verifyServerCertificate=false&useSSL=true
    username: username
    password: password
driverClassName: com.mysql.jdbc.Driver
