INSERT INTO librarydb.countries (id, country_name) VALUES (3, 'Poland');
INSERT INTO librarydb.countries (id, country_name) VALUES (2, 'Russia');
INSERT INTO librarydb.countries (id, country_name) VALUES (5, 'UK');
INSERT INTO librarydb.countries (id, country_name) VALUES (1, 'Ukraine');
INSERT INTO librarydb.countries (id, country_name) VALUES (4, 'USA');
INSERT INTO librarydb.publishers (id, publisher_name) VALUES (4, 'ACT');
INSERT INTO librarydb.publishers (id, publisher_name) VALUES (1, 'Alfred A. Knopf');
INSERT INTO librarydb.publishers (id, publisher_name) VALUES (3, 'Korbush');
INSERT INTO librarydb.publishers (id, publisher_name) VALUES (5, 'Lexica');
INSERT INTO librarydb.publishers (id, publisher_name) VALUES (2, 'Simon & Schuster');
INSERT INTO librarydb.authors (id, all_names, first_name, last_name, sex, country_id) VALUES (1, '', 'Anne', 'Rice', 1, 4);
INSERT INTO librarydb.authors (id, all_names, first_name, last_name, sex, country_id) VALUES (2, '', 'William', 'Shakespeare', 0, 5);
INSERT INTO librarydb.authors (id, all_names, first_name, last_name, sex, country_id) VALUES (3, 'Grigorievich', 'Taras', 'Shevchenko', 0, 1);
INSERT INTO librarydb.authors (id, all_names, first_name, last_name, sex, country_id) VALUES (4, 'Nye', 'Jody', 'Lynn', 1, 4);
INSERT INTO librarydb.authors (id, all_names, first_name, last_name, sex, country_id) VALUES (5, 'Asprin', 'Robert', 'Lynn', 0, 4);
INSERT INTO librarydb.authors (id, all_names, first_name, last_name, sex, country_id) VALUES (6, '', 'Andrzej', 'Sapkowski', 0, 3);
INSERT INTO librarydb.authors (id, all_names, first_name, last_name, sex, country_id) VALUES (7, '', 'Glen', 'Cook', 0, 4);
INSERT INTO librarydb.authors (id, all_names, first_name, last_name, sex, country_id) VALUES (8, 'Nikolaevich', 'Lev', 'Tolstoy', 0, 2);
INSERT INTO librarydb.books (id, format, title, publisher_id, publishing_year, number_of_pages) VALUES (1, 1, 'Lestat', 1, 1985, 300);
INSERT INTO librarydb.books (id, format, title, publisher_id, publishing_year, number_of_pages) VALUES (2, 1, 'Macbeth', 2, 1623, 96);
INSERT INTO librarydb.books (id, format, title, publisher_id, publishing_year, number_of_pages) VALUES (3, 1, 'Kobzar', 3, 1840, 115);
INSERT INTO librarydb.books (id, format, title, publisher_id, publishing_year, number_of_pages) VALUES (4, 1, 'Mything in Dreamland', 4, 2004, 300);
INSERT INTO librarydb.books (id, format, title, publisher_id, publishing_year, number_of_pages) VALUES (5, 2, 'Miecz przeznaczenia', 4, 2004, 300);
INSERT INTO librarydb.books (id, format, title, publisher_id, publishing_year, number_of_pages) VALUES (6, 1, 'Bitter Gold Hearts', 4, 1996, 300);
INSERT INTO librarydb.books (id, format, title, publisher_id, publishing_year, number_of_pages) VALUES (7, 1, 'War And Peace Novel', 5, 1996, 760);
INSERT INTO librarydb.books_authors_list (books_list_id, authors_list_id) VALUES (1, 1);
INSERT INTO librarydb.books_authors_list (books_list_id, authors_list_id) VALUES (2, 2);
INSERT INTO librarydb.books_authors_list (books_list_id, authors_list_id) VALUES (3, 3);
INSERT INTO librarydb.books_authors_list (books_list_id, authors_list_id) VALUES (4, 4);
INSERT INTO librarydb.books_authors_list (books_list_id, authors_list_id) VALUES (4, 5);
INSERT INTO librarydb.books_authors_list (books_list_id, authors_list_id) VALUES (5, 6);
INSERT INTO librarydb.books_authors_list (books_list_id, authors_list_id) VALUES (6, 7);
INSERT INTO librarydb.books_authors_list (books_list_id, authors_list_id) VALUES (7, 8);